<?php

namespace LotusBundle\Repository;

/**
 * MaterielCaracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielCaracteristiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
