<?php

namespace LotusBundle\Repository;

/**
 * MaterielFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
