<?php

namespace LotusBundle\Repository;

/**
 * MaterielFamilleCaracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielFamilleCaracteristiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
