<?php

namespace LotusBundle\Repository;

/**
 * ZoneSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneSecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
