<?php

namespace LotusBundle\Repository;

/**
 * ZoneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
