lotus_marque_list:    
    path:   /marque
    defaults:
        _controller: LotusBundle:marque:list       
lotus_marque_add:    
    path:   /marque/add
    defaults:
        _controller: LotusBundle:marque:add
lotus_marque_edit:
    path:   /marque/edit/{id}
    defaults:
        _controller: LotusBundle:marque:edit
    requirements:
        id: \d*
        
lotus_materiel_list:    
    path:   /materiel
    defaults:
        _controller: LotusBundle:Materiel:list       

lotus_materiel_add:    
    path:   /materiel/add
    defaults:
        _controller: LotusBundle:Materiel:add

lotus_materiel_edit:
    path:   /materiel/edit/{id}
    defaults:
        _controller: LotusBundle:Materiel:edit
    requirements:
        id: \d*


lotus_materielfamille_list:    
    path:   /materielfamille
    defaults:
        _controller: LotusBundle:MaterielFamille:list       

lotus_materielfamille_add:    
    path:   /materielfamille/add
    defaults:
        _controller: LotusBundle:MaterielFamille:add

lotus_materielfamille_edit:
    path:   /materielfamille/edit/{id}
    defaults:
        _controller: LotusBundle:MaterielFamille:edit
    requirements:
        id: \d*


lotus_materielfamillecaracteristique_list:    
    path:   /materielfamillecaracteristique
    defaults:
        _controller: LotusBundle:MaterielFamilleCaracteristique:list       

lotus_materielfamillecaracteristique_add:    
    path:   /materielfamillecaracteristique/add
    defaults:
        _controller: LotusBundle:MaterielFamilleCaracteristique:add

lotus_materielfamillecaracteristique_edit:
    path:   /materielfamillecaracteristique/edit/{id}
    defaults:
        _controller: LotusBundle:MaterielFamilleCaracteristique:edit
    requirements:
        id: \d*


lotus_materielcaracteristique_list:    
    path:   /materielcaracteristique
    defaults:
        _controller: LotusBundle:MaterielCaracteristique:list       

lotus_materielcaracteristique_add:    
    path:   /materielcaracteristique/add
    defaults:
        _controller: LotusBundle:MaterielCaracteristique:add

lotus_materielcaracteristique_edit:
    path:   /materielcaracteristique/edit/{id}
    defaults:
        _controller: LotusBundle:MaterielCaracteristique:edit
    requirements:
        id: \d*
        
lotus_image_list:    
    path:   /image
    defaults:
        _controller: LotusBundle:Image:list       

lotus_image_add:    
    path:   /image/add
    defaults:
        _controller: LotusBundle:Image:add

        
lotus_zone_list:    
    path:   /zone
    defaults:
        #_controller: LotusBundle:Zone:list       

lotus_zone_add:    
    path:   /zone/add
    defaults:
        #_controller: LotusBundle:Zone:add

lotus_zone_edit:
    path:   /zone/edit/{id}
    defaults:
        #_controller: LotusBundle:Zone:edit
    requirements:
        #id: \d*
        
